config/routes.rb
Cliqs::Application.routes.draw do
  
  get "posts/ajax_add"
  get "comments/ajax_add"
  get "comments/ajax_add_photo_show"

  get "pages/home"
  get "users/useTicket"
  get "users/acceptInvite"
  get "users/remove_new_user_box"
  
  get "cliqMemberships/ajax_nav_rank"

  resources :users do
    collection do
      get 'changePassword'
      put 'changePassword'
      get 'emailSettings'
      put 'emailSettings'
    end
  end
  resources :sessions #, only: [:new, :create, :destroy]
  resources :cliqs do
    resources :photos
  end
  resources :cliqmemberships
  resources :profiles
  resources :posts
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/account', :to => 'users#index'
  
  match "cliqs/new_invites/:id", :to => 'cliqs#new_invites'
  match "cliqs/create_invites/:id", :to => 'cliqs#create_invites'
  match "cliqs/members/:id", :to => 'cliqs#members'
  
  match "profiles/edit_prof_pic/:id", :to => 'profiles#edit_prof_pic'
  match "profiles/ajax_add_prof_pic/:id", :to => 'profiles#ajax_add_prof_pic'
  match "profiles/update_prof_pic/:id", :to => 'profiles#update_prof_pic'
  
  root :to => 'sessions#new'
  match ':controller(/:action(/:id))'
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :cliq
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  
  mount_uploader :pic, ProfilePicUploader
  
  def image
    @image ||= MiniMagick::Image.open(pic.url)
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_filter :check_profile_ownership, :except => [:show]
  
  def show
    @profile = Profile.find(params[:id])
    @current_cliq = @profile.cliq
    check_cliq_membership(@current_cliq)
    if @profile.user.id == current_user.id
      @is_myprofile = true
    else
      @is_myprofile = false
    end
  end
  
  def edit
    @profile = Profile.find(params[:id])
    @current_cliq = @profile.cliq
  end
  
  def update
    @profile = Profile.find(params[:id])
    @current_cliq = @profile.cliq
    if @profile.update_attributes(params[:profile])
      flash[:success] = "Profile saved"
      redirect_to profile_path(@profile)
    else
      render :edit
    end
  end
  
  def edit_prof_pic
    @profile = Profile.find(params[:id])
    @current_cliq = @profile.cliq
  end
  
  def update_prof_pic
    @profile = Profile.find(params[:id])
    @current_cliq = @profile.cliq
    if @profile.update_attributes(params[:profile])
      flash[:success] = "Profile picture updated!"
      redirect_to profile_path(@profile)
    else
      render 'edit_prof_pic'
    end
  end
  
  def ajax_add_prof_pic
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(params[:profile])
      @success = true
      image = @profile.image
      @width = image['width']
      @height = image['height']
    else
      @success = false
    end
  end
  
  
  
  private
    
    def check_profile_ownership
      if defined?(params[:id])
        profile = Profile.find(params[:id])
        if profile.user.id != current_user.id
          # sorry, not allowed! (we emphasize privacy!)
          flash[:error] = "That's not your profile!"
          redirect_to users_path
        end
      end
    end
  
end

app/views/profiles/ajax_add_prof_pic.js.erb
<%= remotipart_response do %>

<% if @success %>

	$('img.loading').hide();
	
	var imageContainer = $('.img_container');
	imageContainer.prepend("<%=j image_tag @profile.pic.url, :id => 'prof_crop_img' %>");
	var pic = $('#prof_crop_img');
	console.log(pic);
	var img_width = <%= @width %>;
	var img_height = <%= @height %>;
	
	imageContainer.animate({width: img_width, height: img_height}, 800, function() {
		pic.fadeIn(800);
		prepareProfPicJcrop(pic);
	});
	
	

<% end %>


<% end %>

app/views/profiles/edit.html.erb
<h2>Edit Profile</h2>

<%= form_for @profile, :html => {:class => 'form-stacked'} do |f| %>
	<%= render :partial => '/shared/error_messages', :locals => {:model => @profile} %>
	
	<div class=field>
		<%= f.label :quote %><br>
		<%= f.text_area :quote, :class => 'xlarge', :rows => 5 %>
	</div>
	<div class=field>
		<%= f.label :birthdate %><br>
		<%= f.date_select :birthdate, :order => [:month, :day, :year], :start_year => 1900, :end_year => Time.now.year %>
	</div>
	
	<%= f.submit "Save", :class => 'btn primary' %>
	<%= link_to "Cancel", cliq_url(@current_cliq), :class => 'btn secondary' %>
<% end %>

app/views/profiles/edit_prof_pic.html.erb
<h3>Edit profile picture</h3>

	
<%= form_for @profile, :url => "/profiles/update_prof_pic/"+@profile.id.to_s, :html => {:multipart => true, :class => 'form-stacked edit_prof_pic loading'} do |f| %>
	<%= render :partial => '/shared/error_messages', :locals => {:model => @profile} %>
	
	<div class="field">
		<%= f.file_field :pic %>
	</div>
	
	<%= f.submit "Upload", :class => "btn primary uploadPic" %>
	<%= image_tag "loading.gif", :class => "loading" %>
	<%= link_to "Cancel", profile_path(@profile.id), :class => "btn secondary" %>

	
<% end %>

app/views/profiles/edit_prof_pic_with_crop.html.erb
<h3>Edit profile picture</h3>

<div class="left_half">
	
	<%= form_for @profile, :url => "/profiles/update_prof_pic/"+@profile.id.to_s, :html => {:multipart => true, :class => 'form-stacked edit_prof_pic'} do |f| %>
		<%= render :partial => '/shared/error_messages', :locals => {:model => @profile} %>
		
		<div class="field">
			<%= f.file_field :pic %>
		</div>
		
		<%= f.submit "Upload", :class => "btn primary uploadPic" %>
		<%= link_to "Cancel", profile_path(@profile.id), :class => "btn secondary" %>
		
		
	<% end %>
	
</div>

<div class="right_half">
	
	<div class="crop_title">Crop me!</div>
	
	<div class="img_container">
		<%= image_tag "loading.gif", :class => "loading" %>
	</div>
	
	<%= form_for @profile do |form| %>
		<% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
	    	<%= form.hidden_field attribute, :id => attribute %>
		<% end %>
		<%= form.submit "Crop", :class=> 'btn primary crop_btn', :disabled => "disabled" %>
	<% end %>
	
</div>

app/views/profiles/show.html.erb
<% @user = @profile.user %>

<h1><%= @user.name %></h1>

<% if @is_myprofile %>
	<%= link_to "Edit profile", edit_profile_path(@profile) %>
<% end %>

<div class="profile_picture">
	<%= image_tag @profile.pic_url %>
	
	<% if @is_myprofile %>
		<div class="edit_picture">
			<%= link_to 'Change picture', '/profiles/edit_prof_pic/'+params[:id] %>	
		</div>
	<% end %>
</div>

<% if !@profile.quote.blank? %>
	<div class="quote_box">
		<p><%= nl2br(@profile.quote) %></p>
	</div>
<% end %>

<% if !@profile.birthdate.blank? %>
	<div class="info_box">
		<b>Birthdate</b><br/>
		<%= @profile.birthdate.strftime("%B %d, %Y") %>
	</div>
<% end %>