config/routes.rb
Cliqs::Application.routes.draw do
  
  get "posts/ajax_add"
  get "comments/ajax_add"
  get "comments/ajax_add_photo_show"

  get "pages/home"
  get "users/useTicket"
  get "users/acceptInvite"
  get "users/remove_new_user_box"
  
  get "cliqMemberships/ajax_nav_rank"

  resources :users do
    collection do
      get 'changePassword'
      put 'changePassword'
      get 'emailSettings'
      put 'emailSettings'
    end
  end
  resources :sessions #, only: [:new, :create, :destroy]
  resources :cliqs do
    resources :photos
  end
  resources :cliqmemberships
  resources :profiles
  resources :posts
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/account', :to => 'users#index'
  
  match "cliqs/new_invites/:id", :to => 'cliqs#new_invites'
  match "cliqs/create_invites/:id", :to => 'cliqs#create_invites'
  match "cliqs/members/:id", :to => 'cliqs#members'
  
  match "profiles/edit_prof_pic/:id", :to => 'profiles#edit_prof_pic'
  match "profiles/ajax_add_prof_pic/:id", :to => 'profiles#ajax_add_prof_pic'
  match "profiles/update_prof_pic/:id", :to => 'profiles#update_prof_pic'
  
  root :to => 'sessions#new'
  match ':controller(/:action(/:id))'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  
  validates :user_id, :presence => true
  validates :commentable_id, :presence => true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def ajax_add
    @comment = Comment.new(params[:comment])
    @current_cliq = @comment.commentable.cliq
    if @comment.save
      @success = true
      @current_cliq.send_notification_emails(@comment)
    else
      @success = false
    end    
  end
  
  def ajax_add_photos_show
    @comment = Comment.new(params[:comment])
    @current_cliq = @comment.commentable.cliq
    if @comment.save
      @success = true
      @current_cliq.send_notification_emails(@comment)
    else
      @success = false
    end 
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment-list.html.erb
<% num_comments = comments.length %>

<% if num_comments > 0 %>
<div class="comments_container">
<% else %>
<div class="comments_container empty">	
<% end %>
	
	<div class="comments_container_wraparound"></div>
	
	<% if num_comments > 2 %>
		<div class="show_hidden_comments">
			<a href='#'>See all <%= num_comments %> comments</a>
		</div>
		<div class="hidden_comments">
			<% comments[0..(num_comments-3)].each do |comment| %>
				<%= render :partial => 'shared/comment', :locals => { :comment => comment } %>
			<% end %>
		</div>
		<% comments[(num_comments-2)..(num_comments-1)].each do |comment| %>
			<%= render :partial => 'shared/comment', :locals => { :comment => comment } %>
		<% end %>
	<% else %>
		<div class="hidden_comments"></div>
		<% comments.each do |comment| %>
			<%= render :partial => 'shared/comment', :locals => { :comment => comment } %>
		<% end %>
	<% end %>
</div>

app/views/comments/_email_notification.html.erb
<b><%= comment.user.name %></b> has commented on <b><%= comment.commentable.user.name %>'s</b> <%= comment.commentable.class.name.downcase %> in <b><%= comment.commentable.cliq.name %></b>:<br>
<br>
<div style="padding-left: 20px;">
	<%= nl2br(comment.body) %>
</div>
<br>
<% if comment.commentable.class.name == "Post" %>
	Click <%= link_to "here", post_url(comment.commentable, only_path: false) %> to view the post.
<% else %>
	Click <%= link_to "here", cliq_photo_url(comment.commentable.cliq, comment.commentable, only_path: false) %> to view the photo.
<% end %>

app/views/comments/ajax_add.js.erb
<% if @success %>
	var postContainer = $('#<%= @comment.commentable_type.downcase %><%=@comment.commentable_id.to_s %>');
	postContainer.children('.comments_container').show().append("<%= escape_javascript( render(:partial => 'shared/comment', :locals => { :comment => @comment }) ) %>");
<% else %>
	console.log('comment add failure!');
<% end %>

app/views/comments/ajax_add_photos_show.js.erb
<% if @success %>
	$('.add_comment_container').find('textarea').val('').css('height','');
	$('.comments_container').append("<%= escape_javascript( render(:partial => 'shared/comment', :locals => { :comment => @comment }) ) %>");
<% else %>
	console.log('failure!');
<% end %>