config/routes.rb
Cliqs::Application.routes.draw do
  
  get "posts/ajax_add"
  get "comments/ajax_add"
  get "comments/ajax_add_photo_show"

  get "pages/home"
  get "users/useTicket"
  get "users/acceptInvite"
  get "users/remove_new_user_box"
  
  get "cliqMemberships/ajax_nav_rank"

  resources :users do
    collection do
      get 'changePassword'
      put 'changePassword'
      get 'emailSettings'
      put 'emailSettings'
    end
  end
  resources :sessions #, only: [:new, :create, :destroy]
  resources :cliqs do
    resources :photos
  end
  resources :cliqmemberships
  resources :profiles
  resources :posts
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/account', :to => 'users#index'
  
  match "cliqs/new_invites/:id", :to => 'cliqs#new_invites'
  match "cliqs/create_invites/:id", :to => 'cliqs#create_invites'
  match "cliqs/members/:id", :to => 'cliqs#members'
  
  match "profiles/edit_prof_pic/:id", :to => 'profiles#edit_prof_pic'
  match "profiles/ajax_add_prof_pic/:id", :to => 'profiles#ajax_add_prof_pic'
  match "profiles/update_prof_pic/:id", :to => 'profiles#update_prof_pic'
  
  root :to => 'sessions#new'
  match ':controller(/:action(/:id))'
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  attr_accessible :body, :image, :remote_image_url
  
  belongs_to :cliq
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  
  mount_uploader :image, ImageUploader
  
  validates :image, :presence => true
  
  def latest_activity
    times = [self.created_at]
    self.comments.each do |comment|
      times.push(comment.created_at)
    end
    times.max
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def new
    @current_cliq = Cliq.find(params[:cliq_id])
    check_cliq_membership(@current_cliq)
    @photo = Photo.new
  end
  
  def create
     @current_cliq = Cliq.find(params[:cliq_id])
     check_cliq_membership(@current_cliq)
     @photo = Photo.new(params[:photo])
     @photo.cliq_id = @current_cliq.id
     @photo.user_id = current_user.id
     if @photo.save
       @current_cliq.send_notification_emails(@photo)
       flash['success'] = "Photo saved!"
       redirect_to @current_cliq
     else
       flash.now['error'] = "Error saving photo"
       render 'new'
     end
  end
  
  def show
    @current_cliq = Cliq.find(params[:cliq_id])
    check_cliq_membership(@current_cliq)
    @photo = Photo.find(params[:id])
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @success = false
    if @photo.user.id == current_user.id
      if @photo.destroy
        @success = true
      end
    end
  end
  
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_email_notification.html.erb
<b><%= photo.user.name %></b> has added a photo to <b><%= photo.cliq.name %></b>:<br>
<br>
<div style="padding-left: 20px;">
	<%= image_tag photo.image_url %><br>
	<%= nl2br(photo.body) %>
</div>
<br>
Click <%= link_to "here", cliq_photo_url(photo.cliq, photo, only_path: false) %> to view the photo.

app/views/photos/_photo.html.erb
<% author = photo.user %>

<div class="post_super_container" id="photo<%= photo.id.to_s %>">
	
	<div class="post_container">
		
		<% if author.id==current_user.id %>
			<%= link_to 'x', [@current_cliq, photo], :method => :delete, :confirm => "Are you sure you want to delete this photo?", :class => "ex", :remote => true  %>
		<% end %>
		
		<div class="post_picture">
			<%= link_to post_pic_for(author, 90), post_profile(photo) %>
		</div>
		
		<div class="post_right">
		    <%= link_to author.name, post_profile(photo), :class => 'post_author' %> posted a photo
		    
		    <br>
		    <div class="photo_image_container">
		    	<%= link_to cliq_photo_path(@current_cliq, photo) do %>
		    		<%= image_tag photo.image_url(:wall), :class => 'photo_image' if photo.image? %>
		    	<% end %>	
		    </div>
		    
		    <div class="post_body"><%= nl2br(photo.body) %></div>
		    
		    <div class="post_time"><%= format_datetime(photo.created_at) %></div>
		</div>
	    <div class="clear"></div>
	    
	    <button type="button" class="add_comment_btn">
	    	<%= image_tag "icons/comment_icon.png", :width => 25, :height => 25 %>
	    </button>
		
	</div>
	
	<div class="add_comment_container">
  
    	<%= form_for :comment, :url => "/comments/ajax_add", :remote => true, :html => {:class => 'new_comment_form'} do |f| %>
      		<%= f.text_area :body, :class => "add_comment_body expandable", :rows => 4 %>
      		<%= f.hidden_field :user_id, :value => current_user.id %>
      		<%= f.hidden_field :commentable_id, :value => photo.id %>
      		<%= f.hidden_field :commentable_type, :value => "Photo" %>
      		<button type="submit" class="btn primary submit_comment_btn">Comment</button>
			<button type="button" class="btn secondary cancel_comment_btn">Cancel</button>
		<% end %>
      
	</div>
  
	<%= render :partial => "comments/comment-list", :locals => { :comments => photo.comments } %>
	
</div>

app/views/photos/destroy.js.erb
<% if @success %>
	$('#photo<%= @photo.id %>').fadeOut(800, function() { 
		$(this).remove();
		$('#photo_stream<%= @photo.id %>').remove();
	});
<% end %>

app/views/photos/new.html.erb
<h3>Add photo</h3>

<%= form_for [@current_cliq, @photo], :html => {:multipart => true, :class => 'form-stacked loading'} do |f| %>
	<%= render :partial => '/shared/error_messages', :locals => {:model => @photo} %>
	
	<div class="field">
		<%= f.file_field :image %>
	</div>
	
	<div class="field">
		<%= f.label :body, "Description" %>
		<%= f.text_area :body, :rows => 5 %>
	</div>
	
	<%= f.submit "Save", :class => "btn primary" %>
	<%= image_tag "loading.gif", :class => "loading" %>
	<%= link_to "Cancel", cliq_url(@current_cliq), :class => 'btn secondary' %>
<% end %>

app/views/photos/show.html.erb
<div class="photos-show-left">
	
	<div class="big-photo-container">
		<%= image_tag @photo.image_url, :class => 'big-photo' %>
	</div>
	<br>
	<div class="post_picture">
		<%= link_to post_pic_for(@photo.user, 90), post_profile(@photo) %>
	</div>
	
	<div class="post_right">
	    <%= link_to @photo.user.name, post_profile(@photo), :class => 'post_author' %>
	    
	    <div class="post_body"><%= nl2br(@photo.body) %></div>
	    
	    <div class="post_time"><%= format_datetime(@photo.created_at) %></div>
	</div>

</div>


<div class="photos-show-right">
	<div class="comments_container">
		<% @photo.comments.each do |comment| %>
			<%= render :partial => 'shared/comment', :locals => { :comment => comment } %>
		<% end %>
	</div>
	
	<div class="add_comment_container">
    	<%= form_for :comment, :url => "/comments/ajax_add_photos_show", :remote => true, :html => {:class => 'new_comment_form'} do |f| %>
      		<%= f.text_area :body, :class => "add_comment_body expandable", :rows => 3 %>
      		<%= f.hidden_field :user_id, :value => current_user.id %>
      		<%= f.hidden_field :commentable_id, :value => @photo.id %>
      		<%= f.hidden_field :commentable_type, :value => "Photo" %>
      		<button type="submit" class="btn primary submit_comment_btn">Comment</button>
		<% end %>
	</div>
</div>

<div class="clear"></div>