config/routes.rb
Cliqs::Application.routes.draw do
  
  get "posts/ajax_add"
  get "comments/ajax_add"
  get "comments/ajax_add_photo_show"

  get "pages/home"
  get "users/useTicket"
  get "users/acceptInvite"
  get "users/remove_new_user_box"
  
  get "cliqMemberships/ajax_nav_rank"

  resources :users do
    collection do
      get 'changePassword'
      put 'changePassword'
      get 'emailSettings'
      put 'emailSettings'
    end
  end
  resources :sessions #, only: [:new, :create, :destroy]
  resources :cliqs do
    resources :photos
  end
  resources :cliqmemberships
  resources :profiles
  resources :posts
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/account', :to => 'users#index'
  
  match "cliqs/new_invites/:id", :to => 'cliqs#new_invites'
  match "cliqs/create_invites/:id", :to => 'cliqs#create_invites'
  match "cliqs/members/:id", :to => 'cliqs#members'
  
  match "profiles/edit_prof_pic/:id", :to => 'profiles#edit_prof_pic'
  match "profiles/ajax_add_prof_pic/:id", :to => 'profiles#ajax_add_prof_pic'
  match "profiles/update_prof_pic/:id", :to => 'profiles#update_prof_pic'
  
  root :to => 'sessions#new'
  match ':controller(/:action(/:id))'
  

end

app/models/cliq.rb
class Cliq < ActiveRecord::Base
  include RegexHelper
  
  has_many :cliq_memberships, :dependent => :destroy
  has_many :users, :through => :cliq_memberships
  has_many :posts
  has_many :photos
  
  validates :name,  :presence => true,
                    :format => {:with => $alpha_num_regex,
                                :message => "can only contain letters, numbers, and the following symbols are allowed: [.] [_] [-]"}
  
  def self.order_stories(posts, photos)
    # creates one array ordered by relevancy (datewise)
    # assumes inputs are ordered by created_at DESC
    stories = [].concat(posts).concat(photos)
    stories.sort{|x,y| y.latest_activity <=> x.latest_activity}
  end
  
  def upcoming_birthdays
    profiles = []
    today = Time.now.month.month + Time.now.day.day
    self.users.each do |member|
      
      prof = member.profiles.where(:cliq_id => self.id).first
      if !prof.blank? && !prof.birthdate.nil?
        birthday = prof.birthdate.month.month + prof.birthdate.day.day
        if today - birthday > 0.day
          birthday += 1.year # account for wraparound december>january
        end
        if birthday-today < 30.day
          # upcoming birthday!
          profiles.concat([prof])
        end
        
      end
    end
    profiles
  end

  def send_notification_emails(object)
    # sends email notifications to each member for post/picture/comment/etc
    users.each do |user|
      cliq_mem = user.cliq_memberships.where(cliq_id: self.id).first
      if cliq_mem.receives_email_for(object) && user.id != object.user.id
        UserMailer.notification_email(object, user).deliver
      end
    end
  end
  handle_asynchronously :send_notification_emails

  
end

app/controllers/cliqs_controller.rb
class CliqsController < ApplicationController
  include TicketsHelper
  before_filter :cliqcont_check_cliq_membership, :except => [:new, :create]
  
  def show
    @cliq = Cliq.find(params[:id])
    @current_cliq = @cliq
    @posts = @current_cliq.posts.order("created_at DESC")
    @photos = @current_cliq.photos.order("created_at DESC")
    @stories = Cliq.order_stories(@posts, @photos)
    @upcoming_birthdays = @cliq.upcoming_birthdays
  end

  def new
    @cliq = Cliq.new
  end

  def create
    @cliq = Cliq.new(params[:cliq])
    if @cliq.save
      current_user.cliqs << @cliq
      current_user.profiles << Profile.new({:cliq_id => @cliq.id});
      send_cliq_invites(params[:invites], params[:invite_message], @cliq, current_user)
      flash[:success] = "New cliq created!"
      redirect_to users_path
    else
      @invites = params[:invites]; @invite_message = params[:invite_message]
      render :new
    end
  end
  
  def new_invites
    @current_cliq = Cliq.find(params[:id])
  end
  
  def create_invites
    @current_cliq = Cliq.find(params[:id])
    send_cliq_invites(params[:invites], params[:invite_message], @current_cliq, current_user)
    flash[:success] = "Invites sent!"
    redirect_to @current_cliq
  end
  
  def members
    @current_cliq = Cliq.find(params[:id])
    @members = @current_cliq.users
  end
  
  private
    
    def cliqcont_check_cliq_membership
      if defined?(params[:id])
        check_cliq_membership(Cliq.find_by_id(params[:id]))
      end
    end
    
  
end

app/views/cliqs/_upcoming-birthdays.html.erb
<div class="upcoming_birthdays">
	<b>Upcoming birthdays</b>
	<% today = Time.local(Time.now.year, Time.now.month, Time.now.day) %>
	<% profiles.each do |prof| %>
		<br>
		<% birthday = Time.local(Time.now.year, prof.birthdate.month, prof.birthdate.day)%>
		<%= link_to prof.user.name, prof %> - 
		<% if today == birthday %>
			Today!
		<% elsif birthday == today + 1.day || birthday + 1.year == today + 1.day %>
			Tomorrow
		<% else %>
			<%= birthday.strftime("%b %d") %>
		<% end %>
	<% end %>
</div>

app/views/cliqs/members.html.erb
<h2>Members of <%= @current_cliq.name %></h2>
	
<% @members.each do |member| %>
	<div class="member_link_container">
		<%= link_to member.profiles.where(:cliq_id => @current_cliq.id).first, :class => "member_image" do %>
			<%= post_pic_for(member, 90) %>
			<div class="member_name">
				<%= member.first_name %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/cliqs/new.html.erb
<% @title = "Create Cliq" %>

<h1>Create new Cliq!</h1>

<%= form_for(@cliq, :html => {:class => "form-stacked loading"} ) do |f| %>

	<%= render :partial => 'shared/error_messages', :locals => { :model => @cliq } %>
	
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, :class => 'xxlarge' %>
	</div>
	
	<div class="field">
		<%= label_tag :invites, "Invites (optional)" %>
		<%= text_area_tag :invites, @invites,
			:class => 'xxlarge',
			:size => '30x6',
			:placeholder => 'Enter emails of your favorite people, separated by commas'	%>
	</div>
	
	<div class="field">
		<%= label_tag :invite_message, "Invite message (optional)" %>
		<%= text_area_tag :invite_message, @invite_message,
			:class => 'xxlarge',
			:size => '30x6',
			:placeholder => 'Add a customized message to your invite email'	%>
	</div>
	
	<%= f.submit "Create", :class => 'btn primary' %>
	<%= image_tag "loading.gif", :class => "loading" %>
	<%= link_to "Cancel", users_url, :class => 'btn secondary' %>

<% end %>

app/views/cliqs/new_invites.html.erb
<h1>Send invites</h1>

<%= form_tag('/cliqs/create_invites/'+@current_cliq.id.to_s, :class => "form-stacked" ) do %>
	
	<div class="field">
		<%= label_tag :invites, "Invites" %>
		<%= text_area_tag :invites, @invites,
			:class => 'xxlarge',
			:size => '30x6',
			:placeholder => 'Enter emails of your favorite people, separated by commas'	%>
	</div>
	
	<div class="field">
		<%= label_tag :invite_message, "Invite message" %>
		<%= text_area_tag :invite_message, @invite_message,
			:class => 'xxlarge',
			:size => '30x6',
			:placeholder => 'Add a customized message to your invite email'	%>
	</div>
	
	<%= submit_tag "Send", :class => 'btn primary' %>
	<%= link_to "Cancel", cliq_url(@current_cliq), :class => 'btn secondary' %>

<% end %>

app/views/cliqs/show.html.erb
<div id="left_sidebar">
	<%= link_to "Invite new members", '/cliqs/new_invites/'+@current_cliq.id.to_s, :class => 'btn secondary' %>
	<%= render :partial => 'cliqs/upcoming-birthdays', :locals => {:profiles => @upcoming_birthdays} unless @upcoming_birthdays.length == 0 %>
</div>

<div id="cliq_index_content">
	
	<button type="button" class="btn secondary" id="new_post_btn">New Post</button>
	
	<div id="new_post_container">
		<%= form_for :post, :url => "/posts/ajax_add", :remote => true, :html => {:class => 'new_post_form'} do |f| %>
			<div class="field">
				<%= f.text_area :body, :class => 'add_post_body expandable', :rows => 8 %>
			</div>
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.hidden_field :cliq_id, :value => @current_cliq.id %>
			<%= f.submit "Post", :class => 'btn primary' %>
		<% end %>
		
	</div>
	
	<div id="post_wall">
		
		<% @stories.each do |story| %>
			<%= render :partial => 'photos/photo', :locals => { :photo => story } if story.class.name=="Photo" %>
			<%= render :partial => 'shared/post', :locals => { :post => story } if story.class.name=="Post" %>
		<% end %>
		
	</div><!-- end post_wall -->
	
</div><!-- end cliq_index_content -->

<div id="right_sidebar">
	<%= link_to "New photo", new_cliq_photo_path(@current_cliq), :class => 'btn secondary' %>
	
	<% @photos.each do |photo| %>
		<div class="photo_stream_container">
			<%= link_to cliq_photo_path(@current_cliq, photo) do %>
				<%= image_tag photo.image_url(:square), :class => 'photo_stream', :id => 'photo_stream'+photo.id.to_s if photo.image? %>
			<% end %>
		</div>
	<% end %>
	
	<% if @photos.length == 0 %>
		<br><br>No photos yet!
	<% end %>
</div>